### ISSUE TITLE
toggle only goes to full screen

### ISSUE THREAD

**Issue by jasonmac** [defunkt/Zen#52] opened 2015-03-03 19:22 UTC
When pressing cmd-ctrl-z Full screen is engaged along with Zen. cmd-ctrl-shift-F does nothing.

These toggles previously worked prior to update.
just updated to version 0.11.0

**Comment by braver** [comment] 2015-03-03 21:41
I just had a repro on this, then upgraded to Atom 0.186, and now the problem is gone. The keybinding is there, and the resolver doesn't show any issues either. Mystery :whale: 
Could you try and update Atom to see if that fixes anything, and if it doesn't report what the keybinding resolver is seeing?

**Comment by jasonmac** [comment] 2015-03-04 02:50
I was testing this on .184. I just updated to .186 and still present. Keybinding resolver shows toggling the "not(.mini)"

Here is what is in zen.cson (only showing OS X)
'.platform-darwin atom-workspace':
  'ctrl-shift-cmd-F': 'zen:toggle'
  'cmd-ctrl-z': 'zen:toggle'
'.platform-darwin atom-workspace atom-text-editor:not(.mini)':
  'ctrl-shift-cmd-F': 'zen:toggle'
  'cmd-ctrl-z': 'zen:toggle'

**Comment by braver** [comment] 2015-03-06 09:15
I'm not able to reproduce this on my system.

**Comment by braver** [comment] 2015-03-24 22:03
@jasonmac What I discovered is that Zen doesn't really work properly when you've got multiple Atom windows. It seems the first window does toggle, but the others don't. The keybinding resolver does pick it up in all windows, but nothing happens. I'm not sure what's causing this. Could this be linked to the problem you're seeing?

**Comment by jasonmac** [comment] 2015-03-25 17:40
I just tested it to make sure and on my machine, I have one window open with only one tab. Weird. At least it's not a bug that prevents single project usability, as long as you can live with it being in full screen, ha. :)

**Comment by braver** [comment] 2015-03-25 17:55
well just :weary: :gun: I don't get it.

`cmd-ctrl-z` does work properly though right?

**Comment by jasonmac** [comment] 2015-03-25 18:08
`cmd-ctrl-z` is what I press and it takes me to fullscreen Zen. Like I said, it's still functional, just only full screen. I have also tried `cmd-ctrl-shift -f` and it also takes me into full screen (as that key stroke should, though).

**Comment by braver** [comment] 2015-07-03 20:06
No new sightings of this in a while and lots of changes in Atom. I'm closing this until someone comes with a real solid repo on a recent version.

**Closed by braver** 2015-07-03 20:06 UTC
