### ISSUE TITLE
Line number

### ISSUE THREAD

**Issue by miguelcarax** [defunkt/Zen#81] opened 2015-09-10 19:17 UTC
I go zen mode but i'm seeing line number anyways, i have read here that unchecking Shadow DOM it's solved, but that doesn't work. I have 0.16.2 versión.

**Comment by rm-code** [comment] 2015-09-10 21:35
![screenshot 2015-09-10 23 33 58](https://cloud.githubusercontent.com/assets/11627131/9801624/7e9b934a-5814-11e5-9ce3-94d03efc45c4.png)

Hello! Is the gutter in your preferences?

**Comment by miguelcarax** [comment] 2015-09-10 21:59
it is, checked or unchecked line number continous appearing

**Comment by rm-code** [comment] 2015-09-10 22:03
Which theme are you using?

**Comment by miguelcarax** [comment] 2015-09-10 22:04
Atom Material + Solarized Dark

**Comment by rm-code** [comment] 2015-09-15 17:01
Ok strange ... I can't reproduce it over here at all. 

Are you using any other plugins? Might be worth trying to deactivate them.

**Comment by miguelcarax** [comment] 2015-09-21 12:21
I'm not using nothing unusual...

I have right now: alignment, fonts, file-icons, linter, set-syntax, terminal-plus, tool-bar, tool-bar-almighty, clipboard-history.

**Comment by braver** [comment] 2015-10-07 15:54
I can't reproduce it and I'm not going to hunt down incompatible packages by hand, so I simply don't have the time to investigate this. If there is a clear and particular case I'll look into it, but as it is I'm closing this one.

**Closed by braver** 2015-10-07 15:54 UTC
